backend:
  repository: docker.arvancloud.ir/mhchah/negar-backend
  # repository: docker.arvancloud.ir/mhchah/imagebuilder
  #repository: negar-backend
  pullPolicy: IfNotPresent
  #pullPolicy: Always
  # tag: v0.0.3
  tag: v0.10.18
  replicaCount: 0
  port: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "1500Mi"
      cpu: "2000m"
    limits:
      memory: "1500Mi"
      cpu: "2000m"
postgres:
  repository: postgres
  tag: "16.3"
  pullPolicy: IfNotPresent
  replicaCount: 0
  port: 5432
  service:
    type: ClusterIP
    port: 5432
  resources:
    requests:
      memory: "1500Mi"
      cpu: "1000m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"
  pvc:
    storage: "3Gi"
frontend:
  repository: docker.arvancloud.ir/mhchah/negar-frontend
  # repository: docker.arvancloud.ir/mhchah/imagebuilder
  pullPolicy: IfNotPresent
  tag: v0.16.0
  # tag: v0.0.8
  replicaCount: 0
  port: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "256Mi"
      cpu: "1000m"
    limits:
      memory: "256Mi"
      cpu: "1000m"
abrimentImagePullSecret:
  name: negar-abrsecret
