apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configs
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  HOST: "postgres"
  PORT: "{{ .Values.postgres.port }}"
  POSTGRES_CONNECTION_STRING: "Host=postgres;Database=postgres;Username=postgres;Password=postgres;"
