apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.repository }}:{{ .Values.postgres.tag }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: POSTGRES_DB
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: PORT
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
          resources:
            requests:
              memory: {{ .Values.postgres.resources.requests.memory }}
              cpu: {{ .Values.postgres.resources.requests.cpu }}
            limits:
              memory: {{ .Values.postgres.resources.limits.memory }}
              cpu: {{ .Values.postgres.resources.limits.cpu }}
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-pvc
