apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.service.port }}
