apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    app: postgres
